### ISSUE TITLE
IE9 Debug Console Bind

### ISSUE THREAD

**Issue by douglas-johnson** [athletics/AdManager#25]
@matthewspencer 

I was testing some aspects of Shop Catalog in IE9 and noticed an error which I narrowed down to Ad Manager. 

[Line #48 of src/Util.js](https://github.com/athletics/AdManager/blob/master/src/Util.js#L48) Uses `console.log.bind`

In other cases on SC where that debug pattern is applied, this is used instead...
`return Function.prototype.bind.call( console.log, console );`

I believe Modernizr polyfills the prototype.bind, but maybe not the console.log.bind. Is it possible to switch that in Ad Manager?

**Comment by matthewspencer** [comment]
@douglas-johnson Thanks for the feedback. We’ll change how this works in the next release.

**Comment by douglas-johnson** [comment]
@matthewspencer Awesome, thanks! Just for reference, here's a screenshot of the error message, 

![sc-ie9-js-error](https://cloud.githubusercontent.com/assets/226381/9089967/df27d802-3b65-11e5-906e-070c48f52b02.jpg)

**Comment by matthewspencer** [comment]
@douglas-johnson This is resolved in version 0.6.2.
